# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_auto_20170411_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('image', models.ImageField(blank=True, upload_to='projects')),
                ('content', mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='External URL')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
    ]
